name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd app/client 
          yarn
      - name: Linting
        run: |
          cd app/client 
          yarn lint

  testing:
    runs-on: ubuntu-latest
    needs: linting
    env:
      NEXT_PUBLIC_STRAPI_URL: http://localhost:1337
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd app/client 
          yarn install
      - name: Testing
        run: |
          cd app/client 
          yarn test

  building:
    runs-on: ubuntu-latest
    needs: visualTesting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          npm install typescript --global
          cd app/client 
          yarn install
          cd ../strapi
          yarn install
      - name: Build
        run: |
          cd app/client 
          npx tsc
          cd ../strapi
          yarn tsc

  deploy:
    runs-on: ubuntu-latest
    needs: building
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH-ключа
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.DEPLOY_PATH }}
            git reset --hard origin/main  
            git pull origin main          
            chmod +x start.sh             
            ./start.sh 
          EOF
